### ISSUE TITLE
Use IFileProvider

### ISSUE THREAD

**Issue by hishamco** [aspnet/live.asp.net#113]
@DamianEdwards I notice that you are using `File` class in `DeploymentService`, I change it using the new ASP.NET FileSystem, so there 're a lot of benifits one of them `async` support. If this fine with you I will submit my changes

**Comment by DamianEdwards** [comment]
The call site is a property anyway, so no benefit from async. Plus, the file providers use the same APIs under the covers, and you'd have to initialize your own instance as the one provided for `ContentRoot` is rooted there and you can't traverse out of it, which I need to in order to get the Kudu active deployment file.

I don't think it adds anything in this case.
