### ISSUE TITLE
Allow people to download an ICS file (Outlook) for the next show

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/live.asp.net#18]

**Comment by shanselman** [comment]
Thought. This seems to have Outlook subscribe to a new calendar (the whole calendar and not just add the one event?) That means it doesn't get added to your main calendar, plus we have just one event and not a feed.

Is this the desired behavior?

**Comment by TimMurphy** [comment]
@shanselman relevant for issue #26 (Add to Google Calendar)?

I prefer add the next standup to my main calendar.

**Comment by shanselman** [comment]
Looks like it. It think we want a calendar ITEM to be made (like
Meetup.com/EventBrite.com) rather than a CALENDAR being made. Your turn,
Tim. ;)

On Thu, Aug 6, 2015 at 4:22 PM, Tim Murphy notifications@github.com wrote:

> @shanselman https://github.com/shanselman relevant for issue #26
> https://github.com/aspnet/live.asp.net/issues/26 (Add to Google
> Calendar)?
> 
> I prefer add the next standup to my main calendar.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/aspnet/live.asp.net/issues/18#issuecomment-128537622.

## 

Scott Hanselman
Donate to fight diabetes: http://hnsl.mn/fightdiabetes

**Comment by DamianEdwards** [comment]
Yeah I was thinking about this. `webcal://` is pretty powerful and lets you push updates and do recurring and all types of wonderful, and it works in places that ICS doesn't. But, ICS is well understood and simple, and we don't use those webcal features (yet).

I propose we have a way to let the user decide, e.g. a bootstrap dropdown that lists the different formats. So you click "Add to calendar" and a dropdown appears with the options:
- Download ICS file
- Subscribe using webcal://
- Add to Google Calendar

**Comment by Brad-Christie** [comment]
Not to revive an old thread, but I'm always playing "catch up" with these videos because my calendar doesn't update.

Along the lines of what @shanselman was suggesting, can we leverage [`X-PUBLISHED-TTL:PT1D`](http://msdn.microsoft.com/en-us/library/ee178699%28v=exchg.80%29.aspx) in the iCal and have Outlook fetch an update automatically (for the next event)? That would at least satisfy outlook users (which most .net junkies are ;-) Then you're also not downloading an inclusive list of meetings, but simply checking when the next one is.

Just a thought. I can PR this if it seems fitting.
