### ISSUE TITLE
Low Google PageSpeed Insights score

### ISSUE THREAD

**Issue by cgrantnz** [aspnet/live.asp.net#50]
Currently the live site gets 72/100 for desktop and 52/100 for mobile https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Flive.asp.net%2F&tab=mobile I showed the site to a Ruby dev friend and he wasn't kind about that pagespeed score... If I submit a PR that bumps it up without doing anything weird will you take a look at it?

![Image of PageSpeed Insights score](https://i.imgur.com/JSSBlLh.png)

**Comment by hishamco** [comment]
Thanks @callumelgrant, let us know the fixes that may improve the speed, also I will check it too using using `Web Developer Checklist`

**Comment by hishamco** [comment]
BTW @callumelgrant can you check staging environment https://asp-standup-staging.azurewebsites.net/ because the recent PRs doesn't reflect immediately until it's stable

**Comment by hishamco** [comment]
The staging got 79/100, @callumelgrant be freely to submit a PR if it improves the source :smile:

**Comment by DamianEdwards** [comment]
I took a look. Seems we could do the following to improve the score:
- Optimize the home-bg.jpg image
- Inline the site.min.css (modify the `ScriptInliningTagHelper` to support CSS too)
- Configure IIS expiration headers for home-bg.jpg

The other items we're scored lower on are out of our control really (like the ms.js file). I don't really want to defer loading of the bootstrap CSS because that'll result in a potential [FOUC](https://en.wikipedia.org/wiki/Flash_of_unstyled_content).

**Comment by hishamco** [comment]
:+1:

**Comment by hishamco** [comment]
@DamianEdwards regarding the second point I prefer to create `StyleInlineTagHelper` because the name `ScriptInliningTagHelper` doesn't make sense to support both inline script and style

**Comment by DamianEdwards** [comment]
@hishamco just change the name of the class, e.g. `ScriptStyleInliningTagHelper`

**Comment by hishamco** [comment]
Sound looks good :smile:
